version: "3.9"
services:
    mediscreen-server:
        image: mediscreen
        ports:
            - 8080:8080
    patient-microservice-server:
        image: patient-microservice
        ports:
            - 8081:8081